# Statistical Learning
## 2.3 Lab: Introduction to Python

### 2.3.1 Basic Commands with Python, Numpy

In [55]:
# imports
import numpy as np
from scipy.stats.stats import pearsonr

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D # for 3D plots

import math

import pandas as pd

import IPython as ipy
import sklearn as skl
import statsmodels as sm
import scipy as sp
import pydot as pdt
import patsy as pat
import glmnet as gln

In [61]:
# notebook setup
%load_ext autoreload
%autoreload 2
%matplotlib inline
pd.set_option('precision', 2) # number precision for pandas
plt.style.use('seaborn') # pretty matplotlib plots

In [33]:
# vector/array creation
x = np.array([1, 6, 2])
y = np.array([1, 4, 3])
len(x), len(y)

(3, 3)

In [3]:
# array operations
x + y

array([ 2, 10,  5])

In [73]:
# R ls() counter part in python or notebook
#dir() #will give you the list of in scope variables:
#globals() #will give you a dictionary of global variables
#locals() #will give you a dictionary of local variables
%who ndarray
%whos
%who_ls

y	 
Variable     Type        Data/Info
----------------------------------
Axes3D       type        <class 'mpl_toolkits.mplot3d.axes3d.Axes3D'>
gln          module      <module 'glmnet' from '/U<...>ages/glmnet/__init__.py'>
ipy          module      <module 'IPython' from '/<...>ges/IPython/__init__.py'>
math         module      <module 'math' from '/Use<...>h.cpython-37m-darwin.so'>
matplotlib   module      <module 'matplotlib' from<...>/matplotlib/__init__.py'>
np           module      <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pat          module      <module 'patsy' from '/Us<...>kages/patsy/__init__.py'>
pd           module      <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
pdt          module      <module 'pydot' from '/Us<...>/site-packages/pydot.py'>
pearsonr     function    <function pearsonr at 0x1103949d8>
plt          module      <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
skl          module      <module 'sklearn' from '/<...>ges/sklearn/

['Axes3D',
 'gln',
 'ipy',
 'math',
 'matplotlib',
 'np',
 'pat',
 'pd',
 'pdt',
 'pearsonr',
 'plt',
 'skl',
 'sm',
 'sns',
 'sp',
 'x',
 'y']

In [18]:
# R rm() counter part in python
del(x,y)

In [69]:
? %magic

Docstring:
Print information about the magic function system.

Supported formats: -latex, -brief, -rest
File:      ~/.virtualenvs/py3ml/lib/python3.7/site-packages/IPython/core/magics/basic.py


In [72]:
# matrix creation
x = np.asmatrix(np.arange(1, 5).reshape(2, 2).transpose())
x
#? np.asmatrix

matrix([[1, 3],
        [2, 4]])

In [42]:
y

array([1, 4, 3])

In [40]:
#matrix operations
np.power(x, 2)

matrix([[ 1,  9],
        [ 4, 16]])